#!/bin/bash

export ENET_IPSEC_VPORT_ENC=24
export ENET_IPSEC_VPORT=27

export ENET_IPSEC_SUBTYPE="19"
export ENET_IPSEC_SUBTYPE_FLAG="-subType ${ENET_IPSEC_SUBTYPE}"

export ENET_IPSEC_ID_AUTO="auto"
export ENET_IPSEC_ID_ENG_ENCRYPT=71
export ENET_IPSEC_ID_ENG_VLAN_POP_ENCRYPT=77
export ENET_IPSEC_DEFAULT_CBS=512000
export ENET_IPSEC_FLAG_TUN_ONLY="-hIPSec 1 1"
export ENET_IPSEC_FLAG_ESP_ENCRYPT="-hESP 1"
export ENET_IPSEC_FLAG_ESP_DECRYPT="-hESP 2"
export ENET_IPSEC_FLAG_ENG_ENCRYPT="-hType ${ENET_IPSEC_ID_ENG_ENCRYPT}"
export ENET_IPSEC_FLAG_ENG_VLAN_POP_ENCRYPT="-hType ${ENET_IPSEC_ID_ENG_VLAN_POP_ENCRYPT}"

export ENET_IPSEC_OUTBOUND_TUNNEL_PARTIAL_OFFLOAD_PRIORITY=2000
export ENET_IPSEC_INBOUND_TUNNEL_PARTIAL_OFFLOAD_PRIORITY=2000
export ENET_IPSEC_OUTBOUND_TUNNEL_FULL_OFFLOAD_PRIORITY=2500
export ENET_IPSEC_INBOUND_TUNNEL_FULL_OFFLOAD_PRIORITY=2500
export ENET_IPSEC_VPORT_VLAN_PUSH_PRIORITY=3000

export ID_OUTBOUND='src %s dst %s proto esp spi %d'
export ID_INBOUND='dst %s src %s proto esp spi %d'
export SELECTOR_OUTBOUND='sel dev %s src %s dst %s'
export SELECTOR_INBOUND='sel dev %s dst %s src %s'
export ALGO_AUTH='auth "%s" %s'
export ALGO_ENC='enc "%s" %s'
export OFFLOAD_OUTBOUND='offload dev %s dmac %s dir out'
export OFFLOAD_INBOUND='offload dev %s dir in'

export OUTBOUND_TUNNEL_SPEC="${SELECTOR_OUTBOUND} ${OFFLOAD_OUTBOUND}"
export INBOUND_TUNNEL_SPEC="${SELECTOR_INBOUND} ${OFFLOAD_INBOUND}"

export OUTBOUND_TUNNEL_FULL_OFFLOAD_PATTERN="\
${ID_OUTBOUND} mode ro \
${ALGO_AUTH} \
${ALGO_ENC} \
${OUTBOUND_TUNNEL_SPEC}"
export INBOUND_TUNNEL_FULL_OFFLOAD_PATTERN="\
${ID_INBOUND} mode ro \
${ALGO_AUTH} \
${ALGO_ENC} \
${INBOUND_TUNNEL_SPEC}"

export OUTBOUND_TUNNEL_PARTIAL_OFFLOAD_PATTERN="\
${ID_OUTBOUND} mode tunnel \
${ALGO_AUTH} \
${ALGO_ENC} \
${OUTBOUND_TUNNEL_SPEC}"
export INBOUND_TUNNEL_PARTIAL_OFFLOAD_PATTERN="\
${ID_INBOUND} mode tunnel \
${ALGO_AUTH} \
${ALGO_ENC} \
${INBOUND_TUNNEL_SPEC}"

export OUTBOUND_TUNNEL_SW_OFFLOAD_PATTERN="\
${ID_OUTBOUND} mode tunnel \
${ALGO_AUTH} \
${ALGO_ENC} \
${SELECTOR_OUTBOUND}"
export INBOUND_TUNNEL_SW_OFFLOAD_PATTERN="\
${ID_INBOUND} mode tunnel \
${ALGO_AUTH} \
${ALGO_ENC} \
${SELECTOR_INBOUND}"
